In [1]:
import numpy as np

In [16]:
def sigmoid(number):
    return 1/(1+np.exp(-number))

def deriv(number):
    return number*(1-number)

In [23]:
#initialization
X = np.array(([1,0,0]))
Y = np.array(([1]))
Y = Y.reshape((1,1))

w1 = np.random.random((3,3))#ensure these are not zero otherwise they will not update
w2 = np.random.random((3,1))

In [24]:
w1

array([[ 0.67263324,  0.53845351,  0.39149368],
       [ 0.21795982,  0.4322993 ,  0.53442876],
       [ 0.29496913,  0.01173277,  0.18515359]])

In [25]:
w2

array([[ 0.93392227],
       [ 0.82420618],
       [ 0.29478691]])

In [26]:
#train
l0 = X
l1 = sigmoid(np.dot(l0,w1))
l1 = l1.reshape(1,3)
l2 = np.dot(l1,w2)
l2 = l2.reshape(1,1)

l2_error = Y-l2
l2_delta = l2_error*(deriv(l2)) 

l1_error = np.dot(w2,l2_delta)
l1_delta = l1_error*(deriv(l1))

w2 += np.transpose(np.dot(l2_delta,l1))
w1 += np.dot(l0,l1_delta)

In [27]:
w2

array([[ 1.02011162],
       [ 0.90640691],
       [ 0.37245612]])

In [28]:
w1

array([[ 0.69983282,  0.56674655,  0.42075205],
       [ 0.24515939,  0.46059235,  0.56368713],
       [ 0.32216871,  0.04002581,  0.21441195]])

In [11]:
l2

array([[ 0.]])

In [14]:
l2_error

array([[ 1.]])

In [15]:
deriv(l2)

array([[ 0.]])